# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ant' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ant
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'SVProgressHUD'
  pod 'MJRefresh'
  pod 'TZImagePickerController'
  pod 'SMSSDK'
  pod 'MJExtension'

# shareSDK
  pod 'ShareSDK3'
  pod 'MOBFoundation'
  pod 'ShareSDK3/ShareSDKUI'
  pod 'ShareSDK3/ShareSDKExtension'

  pod 'ShareSDK3/ShareSDKPlatforms/QQ'
  pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
  pod 'ShareSDK3/ShareSDKPlatforms/WeChat'

  pod 'ShareSDK3/ShareSDKPlatforms/Facebook'
  pod 'ShareSDK3/ShareSDKPlatforms/Twitter'

end
